apiVersion: v1
kind: Service
metadata:
  name: spark-pi
spec:
  selector:
    app: spark-pi
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80
      targetPort: 4040  # Assuming this is the port your Spark application exposes
  type: ClusterIP  # Use ClusterIP if you only want internal access, change to NodePort or LoadBalancer for external access
